/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'raincole' at '1/23/17 12:29 AM' with Gradle 3.0
 *
 * @author raincole, @date 1/23/17 12:29 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
